apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dailyfeed-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dailyfeed-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dailyfeed-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "dailyfeed-frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "dailyfeed-frontend.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: NEXT_PUBLIC_MEMBER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "dailyfeed-frontend.fullname" . }}-config
              key: NEXT_PUBLIC_MEMBER_SERVICE_URL
        - name: NEXT_PUBLIC_CONTENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "dailyfeed-frontend.fullname" . }}-config
              key: NEXT_PUBLIC_CONTENT_SERVICE_URL
        - name: NEXT_PUBLIC_TIMELINE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "dailyfeed-frontend.fullname" . }}-config
              key: NEXT_PUBLIC_TIMELINE_SERVICE_URL
        - name: NEXT_PUBLIC_ACTIVITY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "dailyfeed-frontend.fullname" . }}-config
              key: NEXT_PUBLIC_ACTIVITY_SERVICE_URL
        - name: NEXT_PUBLIC_IMAGE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "dailyfeed-frontend.fullname" . }}-config
              key: NEXT_PUBLIC_IMAGE_SERVICE_URL
        - name: NEXT_PUBLIC_SEARCH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "dailyfeed-frontend.fullname" . }}-config
              key: NEXT_PUBLIC_SEARCH_SERVICE_URL
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
